name: simple-pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print message
        run: echo "job1 started"

  job2:
    name: job2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print message
        run: echo "job2 started"

